### PR TITLE
Parsing of PE loadconfig section

### PR DESCRIPTION
**Pull request by ganzm**
made changes to be able to read Control Flow Guard Function table from the Ropper project

### CODE REVIEW

**Comment by sashs** [comment]
Nice! Thank you.

**Comment by sashs** [comment]
Added you to the AUTHORS file.
https://github.com/sashs/filebytes/blob/master/AUTHORS

**Comment by ganzm** [comment]
I also made some changes to ropper to make it Microsoft CFG aware for PE files. You can filter gadgets, so any gadget which does not pass the control flow integrity check will not be shown.

This would be the Visual Studio /guard:cf compile flag.

I am not sure whether I put the filter into the right spot of Ropper. I created a "set/unset cfg" flag to enable/disable filtering.  Do you want a pull request for this change as well?

**Comment by sashs** [comment]
Cool. That would be nice, but the option should be implemented in a different way. 
The set und the unset option are thought for a different thing, e.g. edit the headers (set nx/aslr flag) 
Look at the option.py and add an option there. An object of the Option-Class is used for all options like color, badbytes, all (to show all gadgets, the double gadgets as well).

**Comment by sashs** [comment]
If you want you create a pull request and I will merge it into a dev branch and change the implementation.

**Pull request merged**
